http://localhost:4000/

###
http://localhost:4000/status

###
http://localhost:4000/blocks


###
http://localhost:4000/balance/tmpAddress

###
http://localhost:4000/balance/tmpAddress?total=true

###
POST http://localhost:4000/blocks

###
http://localhost:4000/blocks/3

###
POST http://localhost:4000/transactions         

{
    "To" : "lynn",
    "Amount" : 80
}

###
http://localhost:4000/mempool